### ISSUE TITLE
**Describe the bug**

### ISSUE THREAD

**Issue by octo-0rg** [ekazaev/route-composer#106]
**Describe the bug**

**To Reproduce**

**OR**

1. Create the configuration '...' and apply it to the `Router`
2. See incorrect '....' behaviour 
3. Expected '....' behaviour

*NB: A picture is worth a thousand words. So it is always better to provide a sample project that contains and clearly shows the issue*

**Expected behavior**

**Configuration:**
 - Device: [e.g. iPhone11]
 - OS: [e.g. iOS13.5]
 - RouteComposer version [e.g. 2.6.0]

**Additional context**

_Originally posted by @octo-0rg in https://github.com/ekazaev/route-composer/issues/105_

**Comment by ekazaev** [comment]
@octo-0rg I am closing this issue as incorrect
