### ISSUE TITLE
SwiftPM support missing

### ISSUE THREAD

**Issue by nikislyak** [ekazaev/route-composer#42]
Please add Package.swift manifest to make it accessible through SwiftPM

**Comment by ekazaev** [comment]
@nikislyak It is in my roadmap. Should be there in a week or so.

**Comment by ekazaev** [comment]
@nikislyak The pull request is ready. Can you please have a look? I tested it in the mock app with a package manager and it worked for me.
Thank you

**Comment by nikislyak** [comment]
@ekazaev Thank you so much. I've also tested on my test project and it works fine!

**Comment by ekazaev** [comment]
You are very welcome @nikislyak! Let me know if you will have any issues.
