### ISSUE TITLE
Incorrect tag for Swift Package manager

### ISSUE THREAD

**Issue by ericyanush** [ekazaev/route-composer#44]
Swift package manger always tries to resolve versions using semantic versioning, so when using the tag 2.5, it automatically tries to resolve the tag as 2.5.0, which doesn't exist, so resolving the package fails.

Tested with Xcode 11.3

**Comment by ekazaev** [comment]
@ericyanush Hi. Just added a tag. Can you please confirm that it works as expected?

**Comment by ekazaev** [comment]
@ericyanush It works for me as expected
<img width="280" alt="Screenshot 2020-01-13 at 16 54 34" src="https://user-images.githubusercontent.com/20243258/72275219-67b7a580-3625-11ea-8414-22fb8ebb1357.png">

**Comment by ericyanush** [comment]
The new tag works as expected. Thanks for fixing that so quickly!
