### ISSUE TITLE
Make NavigationDelayingInterceptor context generic

### ISSUE THREAD

**Issue by WingedDoom** [ekazaev/route-composer#54]
Method `.adding(...)` requires that `RI.Context == C`, which means factory and interceptor context types should be equal.

This, however, is not always possible with current implementation of `NavigationDelayingInterceptor`, which has `Context = Any?`.

Adding a generic parameter `Context` to `NavigationDelayingInterceptor` would fix the problem, and it seems easy to do, though I'm not sure how difficult it would be to refactor usages of the interceptor.

**Comment by ekazaev** [comment]
@WingedDoom Good catch. Will do it asap. Thank you

**Comment by ekazaev** [comment]
@WingedDoom I have only one question. I did not expect that this intercepter might be applied to the particular chain of steps. I expected it to be applied to the router once as if that issue exists - it is global to the application.
