### ISSUE TITLE
[Help] Support set root controller direct in AppDelegate 

### ISSUE THREAD

**Issue by toanbuidjv** [ekazaev/route-composer#65]
I want to create project, ViewController with xib file ( not use storyboard), embed with UINavigationControlller
Could you support set root controller direct in AppDelegate and support better with xib file  (not use storyboard) ?
Example:
`func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
RouteComposerDefaults.configureRootViewController(...)
}`
You can reference https://github.com/quickbirdstudios/XCoordinator - simple, easy read & use

**Comment by ekazaev** [comment]
@toanbuidjv Hi, Sorry. I did not really understand your question? Do you want me to help you to setup a project or you want me to use XCoordinator?

**Comment by toanbuidjv** [comment]
I using XCoordinator, feel simple, easy, low code and when switch to "route-composer", feel so hard. Coud you make library to simple, easy understand, full document like XCoordinator?

**Comment by ekazaev** [comment]
Thank you for your feedback. I assume that you found your ideal library. There is nothing wrong with XCoordinator. Just keep using it.
