### ISSUE TITLE
Modular Architecture

### ISSUE THREAD

**Issue by bagusandinata** [ekazaev/route-composer#81]
hi @ekazaev, may i have some enlightenment how to implement RouteComposer in Modular Architecture? I ran into a deadlock in unclean code and how to interaction of each module feature 😅

**Comment by ekazaev** [comment]
@bagusandinata Can you help me to understand something. Do you have every screen in a separate module? If so, then make a Context object and a ViewController public. But DefaultRouter should stay in the main app I assume, if those modules need some navigation - they also need to expose some routing delegate that will be implemented in the main module and below will call Default Router

**Comment by bagusandinata** [comment]
Thanks @ekazaev , I get it 😁 I forgot to check the example, apparently there is a modular implementation
