### ISSUE TITLE
How to change root view controller using LoginInterceptor and then continue navigation

### ISSUE THREAD

**Issue by tadelv** [ekazaev/route-composer#82]
Hi!

I am trying to understand how to compose the navigation for the following case:

- user taps on deep link outside the app (cold boot) to a destination behind a login interceptor
- app opens on splash (landing) and navigates to login (due to interceptor)
- **login succeeds, root is changed from splash to home**
- destination is shown

I've tried to navigate to home in the interceptor, but the subsequent navigation to destination fails, because landing was used for origin view controller.

Any ideas?

P.S.: I'm trying to do this in the example app with the ColorViewController. Here is the diff:
```diff --git a/Example/RouteComposer/Configuration/ExampleConfiguration.swift b/Example/RouteComposer/Configuration/ExampleConfiguration.swift
index 12d2bee8..c42e0b3f 100644
--- a/Example/RouteComposer/Configuration/ExampleConfiguration.swift
+++ b/Example/RouteComposer/Configuration/ExampleConfiguration.swift
@@ -78,6 +78,7 @@ extension ExampleScreenConfiguration {
         StepAssembly(
             finder: ColorViewControllerFinder(),
             factory: ColorViewControllerFactory())
+            .adding(LoginInterceptor<String>())
             .adding(DismissalMethodProvidingContextTask(dismissalBlock: { context, animated, completion in
                 // Demonstrates ability to provide a dismissal method in the configuration using `DismissalMethodProvidingContextTask`
                 UIViewController.router.commitNavigation(to: GeneralStep.custom(using: PresentingFinder()), with: context, animated: animated, completion: completion)
```
```diff --git a/Example/RouteComposer/SceneDelegate.swift b/Example/RouteComposer/SceneDelegate.swift
index 97e20638..0a3dff78 100644
--- a/Example/RouteComposer/SceneDelegate.swift
+++ b/Example/RouteComposer/SceneDelegate.swift
@@ -18,6 +18,17 @@ class SceneDelegate: UIResponder, UIWindowSceneDelegate {
     func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
         ConfigurationHolder.configuration = ExampleConfiguration()
 
+      guard let windowScene = (scene as? UIWindowScene) else { return }
+
+      /// 2. Create a new UIWindow using the windowScene constructor which takes in a window scene.
+      let window = UIWindow(windowScene: windowScene)
+
+      let storyboard = UIStoryboard(name: "PromptScreen", bundle: nil)
+      let controller = storyboard.instantiateInitialViewController()
+
+      window.rootViewController = controller
+      self.window = window
+      
         // Try in mobile Safari to test the deep linking to the app:
         // Try it when you are on any screen in the app to check that you will always land where you have to be
         // depending on the configuration provided.
@@ -26,8 +37,12 @@ class SceneDelegate: UIResponder, UIWindowSceneDelegate {
         // dll://products?product=01
         // dll://cities?city=01
         ExampleUniversalLinksManager.configure()
+
+      window.makeKeyAndVisible()
```

**Comment by tadelv** [comment]
I forgot to add that i would like the destination to open from either the circle view controller or from anywhere the user is currently on (and logged in)

**Comment by ekazaev** [comment]
@tadelv 

Thank you for the question. I am not able to reply right now as I am not by the computer. Ill try to answer your question asap.

**Comment by tadelv** [comment]
Thank you,
There is no rush. I am just getting to know this framework, so it might be
I am trying to tackle this problem from the wrong angle. Let me know if you
need any additional clarification.

**Comment by tadelv** [comment]
@ekazaev I think I have found a way to do it. Find the diff below. Is this the right way to go about it?
I am using a SwitchAssembly to determine the source controller based on the login status of the user.

```diff --git a/Example/RouteComposer/Configuration/ExampleConfiguration.swift b/Example/RouteComposer/Configuration/ExampleConfiguration.swift
index 12d2bee8..51e6887a 100644
--- a/Example/RouteComposer/Configuration/ExampleConfiguration.swift
+++ b/Example/RouteComposer/Configuration/ExampleConfiguration.swift
@@ -78,6 +78,7 @@ extension ExampleScreenConfiguration {
         StepAssembly(
             finder: ColorViewControllerFinder(),
             factory: ColorViewControllerFactory())
+            .adding(LoginInterceptor<String>())
             .adding(DismissalMethodProvidingContextTask(dismissalBlock: { context, animated, completion in
                 // Demonstrates ability to provide a dismissal method in the configuration using `DismissalMethodProvidingContextTask`
                 UIViewController.router.commitNavigation(to: GeneralStep.custom(using: PresentingFinder()), with: context, animated: animated, completion: completion)
@@ -86,7 +87,16 @@ extension ExampleScreenConfiguration {
             .using(ExampleNavigationController.push())
             .from(SingleContainerStep(finder: NilFinder(), factory: NavigationControllerFactory<ExampleNavigationController, String>()))
             .using(GeneralAction.presentModally())
-            .from(GeneralStep.current())
+            .from(SwitchAssembly<UIViewController, String>()
+              .addCase({ _ in
+                guard isLoggedIn == false else {
+                  return nil
+                }
+                return circleScreen.unsafelyRewrapped()
+              })
+                .assemble(default: {
+                  GeneralStep.current()
+                }))
             .assemble()
     }
```

**Comment by tadelv** [comment]
Hey @ekazaev, just pinging, are you still away from the computer? :)

**Comment by ekazaev** [comment]
Hey. Sorry. I am on vacation. Will be back tomorrow 🥹

**Comment by tadelv** [comment]
Ooops! Sorry for bothering you then 🙈

**Comment by ekazaev** [comment]
@tadelv Sorry for the delay. 
If I understood your question correctly here you hit a limitation of the logic. It first searches for the view controller to start as configuration may be incorrect or you can be already on the screen that requires login (and if you are already there it is pointless to show login right?), then if it found the appropriate view controller to start it runs all the gloably assigned interceptors and then individual interceptors. And continues to build the leftover route after all the Interceptors succeded. 

The problem here is that you can't change what router considers as a partialy build stack as correct from the interceptor. For example, if you are on HomePage as origin, you want to navigate somewhere but in the Interceptor you want to change the origin as well. I did not implement it as it will make the router logic to complex, hard to explain and hard to debug. But it is also a rare case as for the intermediate login full screen modal is usually used and then navigation continues.

But if it is necessary, the GlobalInterceptorRouter wrapper can help you. You can add your interceptor to it and it will run an interceptror before the main router starts to work. Then only thing is you can not parse the configuration from that wrapper so youll have to mark all the contexts that require to have a login somehow. For example with an empty protocol `LoginRequiring`.

Then you can write your global interceptor like 

```
    func perform(with context: Any?, completion: @escaping (_: RoutingResult) -> Void) {
        guard let loginRequiringContext = context as? LoginRequiring else {
            completion(.success)
            return
        }
        // Otherwise check if user is logged in and if not - do whatever you want with the stack as the MainRouter hasnt started to work yet
```

Hope I understood your question correctly. Please let me know.

**Comment by tadelv** [comment]
Hey @ekazaev thanks for taking the time to write this exhaustive answer. 

Let me see if I got it right: The global interceptors run before router decides which will be the originating (root) view controller? So this means, they can change the view controller hierarchy before origin VC is selected?
I assume this will definitely be cleaner than the current solution. But on the other hand, I could package the SwitchAssembly into a property of the configuration and just use it where i need it - though it will still introduce complexity which would be abstracted away by the global interceptor.
The app I'm planning to build using route-composer has most of the screens behind login, but some of them require a specific navigation stack to be built and some can be presented on any current view controller visible (when authenticated), i.e. a certain detail view will require to have a list view in the stack, but a certain other detail view will be presented modally anywhere, requiring only that the user is logged in (and the correct rootVC is there).
The app is divided into two states (which have their own rootVCs), logged in and not logged in. In normal operation, the user starts with the not-logged-in state and after authenticating, the rootVC is changed (let's say to a tab bar view controller).

Hope it makes sense. Let me know please if my assumptions regarding global interceptor are correct

**Comment by tadelv** [comment]
Just a quick update - I was able to get it to work the way you proposed, using a GlobalInterceptor and replacing the root view controller in there.

```diff --git a/Example/RouteComposer/Extensions/ViewController.swift b/Example/RouteComposer/Extensions/ViewController.swift
index 31ddbf30..dda355c3 100644
--- a/Example/RouteComposer/Extensions/ViewController.swift
+++ b/Example/RouteComposer/Extensions/ViewController.swift
@@ -11,6 +11,8 @@ import os.log
 import RouteComposer
 import UIKit
 
+protocol RequiresLogin {}
+
 extension UIViewController {
 
     // This class is needed just for the test purposes
@@ -29,8 +31,53 @@ extension UIViewController {
         }
     }
 
+
+
+  private final class GlobalLoginInterceptor<C>: RoutingInterceptor {
+    typealias Context = C
+
+    func perform(with context: Context, completion: @escaping (RoutingResult) -> Void) {
+      guard context is RequiresLogin else {
+        completion(.success)
+        return
+      }
+      guard isLoggedIn == false else {
+        completion(.success)
+        return
+      }
+      let destination = LoginConfiguration.login()
+      do {
+        try UIViewController.router.navigate(to: destination) { routingResult in
+          guard routingResult.isSuccessful,
+                let viewController = ClassFinder<LoginViewController, Any?>().getViewController() else {
+            completion(.failure(RoutingError.compositionFailed(.init("LoginViewController was not found."))))
+            return
+          }
+
+
+          viewController.interceptorCompletionBlock = { result in
+            guard case .success = result else {
+              completion(result)
+              return
+            }
+            do {
+              try viewController.router.navigate(to: ExampleConfiguration().homeScreen, animated: false) { result in
+                completion(result)
+              }
+            } catch {
+              completion(.failure(error))
+            }
+          }
+        }
+      } catch {
+        completion(.failure(RoutingError.compositionFailed(.init("Could not present login view controller", underlyingError: error))))
+      }
+    }
+  }
+
     static let router: Router = {
         var defaultRouter = GlobalInterceptorRouter(router: FailingRouter(router: DefaultRouter()))
+      defaultRouter.addGlobal(GlobalLoginInterceptor<Any?>())
         defaultRouter.addGlobal(TestInterceptor("Global interceptors start"))
         defaultRouter.addGlobal(NavigationDelayingInterceptor(strategy: .wait))
         defaultRouter.add(TestInterceptor("Router interceptors start"))```

**Comment by ekazaev** [comment]
@tadelv  are you happy with the result? 
I am really sorry for the late replies. I have nine weddings to attend this year so my availability is terrible 🥹

**Comment by tadelv** [comment]
Hey @ekazaev, 
I think I have what I need. I was only researching the approaches in the example app in this repo. When I start using route-composer in the production app, I will decide whether to use the configuration approach or the GlobalInterceptor. I think it will depend whether I will have many configurations and whether I can provide different contexts for the interceptor.
But for now, my questions have been answered, thanks a lot!

Good luck with all the weddings 😆
