### ISSUE TITLE
Have different contexts for Factory and navigation

### ISSUE THREAD

**Issue by vykut** [ekazaev/route-composer#92]
Hello,

After we have replaced *most* of the navigation logic in our app with the APIs from this library, we have come across, what one might think of, a limitation of the `Context` approach. Currently, `Factory` & `ContextAccepting` protocols both expect a `Context` type, which, theoretically, can be different, but in practice we realized that it actually has to be the same.

Practically, How can I use a different `Context` type for *creating* a ViewController via `Factory` and a different `Context` for navigating to such controller and "injecting" a different state?

the `Router` method `navigate` accepts a single type of `Context`, so having 2 different types of `Context`s - one for `Factory` and one for `ContextSettingTask` is currently not possible.

**Comment by ekazaev** [comment]
@vykut Thank you for your questions. Could you please read those answers here https://github.com/ekazaev/route-composer/issues?q=is%3Aissue+is%3Aclosed++hotel in the closed issues. I believe there a variety of good explanations why is that so. If it wont be enough - please ping me here and we can discuss your particular case.

**Comment by vykut** [comment]
Thank you @ekazaev for pointing me to those other issues. Really useful!
