### ISSUE TITLE
Add dependency registration via SPM to Readme

### ISSUE THREAD

**Issue by Nikitos9I** [ekazaev/route-composer#99]
Hello! Thank you for your framework. Could you please add dependency addition via swift package manager?

**Comment by ekazaev** [comment]
Hi @Nikitos9I,

Thank you for your request. I"would love to but what exactly do you mean? I didn't keep up recently with the SPM features and quick googling didn't help. Can you please explain what do you mean and I will add it with a pleasure. 

Eugene

**Comment by Nikitos9I** [comment]
That is all about Readme file) Like Moya repo https://github.com/Moya/Moya#swift-package-manager

**Comment by ekazaev** [comment]
Will do. Thanks

**Comment by ekazaev** [comment]
@Nikitos9I Hi. 

I have added a simple description. Please check it out and close the issue if you are satisfied with the result.

**Comment by Nikitos9I** [comment]
@ekazaev Thank you!
